### ISSUE TITLE
 Error reading configuration: Unsupported Config Type "" &  Could not find configtx.yaml

### ISSUE THREAD

**Issue by AldrinAJ** [awsdocs/amazon-managed-blockchain-management-guide#1]
Hi @Pahtoe 
I could accompilsh the procedures from creating the network and first member, till the below, where i get error, 

https://docs.aws.amazon.com/managed-blockchain/latest/managementguide/get-started-create-channel.html

When i try to generate the configtx peer block using:
docker exec cli configtxgen \
-outputCreateChannelTx /opt/home/mychannel.pb \
-profile OneOrgChannel -channelID mychannel \
--configPath /opt/home/

i get the below error:
2020-04-29 16:49:39.398 UTC [common/tools/configtxgen] main -> INFO 001 Loading configuration
2020-04-29 16:49:39.398 UTC [common/tools/configtxgen/localconfig] Load -> CRIT 002 Error reading configuration: Unsupported Config Type ""
2020-04-29 16:49:39.398 UTC [common/tools/configtxgen] func1 -> ERRO 003 Could not find configtx.yaml. Please make sure that FABRIC_CFG_PATH or --configPath is set to a path which contains configtx.yaml

I have kept the config files in the home/ec2-user directory: 
$ls
admin-msp                        fabric-samples                      go1.10.3.linux-amd64.tar.gz
configtx.yaml                          get-pip.py                        managedblockchain-tls-chain.pem
docker-compose-cli.yaml                      go

+ i tried export FABRIC_CFG_PATH=$PWD,
but it throws the same error..
Kindly advice,
what might be the cause and how can i resolve it? Could you please advice me? Thanks

**Comment by AldrinAJ** [comment]
its a typo from my side, I apologize..

**Comment by ghost** [comment]
@AldrinAJ Glad you caught it and were able to fix it. Honestly, that file is a pain. One suggestion for future--if you hit errors like this, or have other questions, try the support forum at https://forums.aws.amazon.com/forum.jspa?forumID=342. There are multiple people monitoring that forum with much deeper expertise than I have, and you're likely to get help more quickly than you would here. Thanks for using Managed Blockchain. Hope you're building something cool and having some fun!

**Comment by AldrinAJ** [comment]
Yeah sure, Thanks @Pahtoe 
Thanks for the support link..
